import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
 
export const THEME = {
  light: {
    background: '#f5f5ff',
    foreground: '#2a2a4a',
    card: '#ffffff',
    cardForeground: '#2a2a4a',
    popover: '#ffffff',
    popoverForeground: '#2a2a4a',
    primary: '#6e56cf',
    primaryForeground: '#ffffff',
    secondary: '#e4dfff',
    secondaryForeground: '#4a4080',
    muted: '#f0f0fa',
    mutedForeground: '#6c6c8a',
    accent: '#d8e6ff',
    accentForeground: '#2a2a4a',
    destructive: '#ff5470',
    destructiveForeground: '#ffffff',
    border: '#e0e0f0',
    input: '#e0e0f0',
    ring: '#6e56cf',
    radius: '0.5rem',
    chart1: '#6e56cf',
    chart2: '#9e8cfc',
    chart3: '#5d5fef',
    chart4: '#7c75fa',
    chart5: '#4740b3',
  },
  dark: {
    background: '#0f0f1a',
    foreground: '#e2e2f5',
    card: '#1a1a2e',
    cardForeground: '#e2e2f5',
    popover: '#1a1a2e',
    popoverForeground: '#e2e2f5',
    primary: '#a48fff',
    primaryForeground: '#0f0f1a',
    secondary: '#2d2b55',
    secondaryForeground: '#c4c2ff',
    muted: '#222244',
    mutedForeground: '#a0a0c0',
    accent: '#303060',
    accentForeground: '#e2e2f5',
    destructive: '#ff5470',
    destructiveForeground: '#ffffff',
    border: '#303052',
    input: '#303052',
    ring: '#a48fff',
    radius: '0.5rem',
    chart1: '#a48fff',
    chart2: '#7986cb',
    chart3: '#64b5f6',
    chart4: '#4db6ac',
    chart5: '#ff79c6',
  },
};
 
export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
